name: Execute Notebook

on:
  push:
  pull_request:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install nbconvert

    - name: Run notebook
      run: |
        jupyter nbconvert --to notebook --execute notebook/iadt_fase01_final.ipynb --output executed_notebook.ipynb
