name: Execute Notebook

on:
  push:
  pull_request:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install nbconvert flake8

    - name: Check code style
      run: flake8 notebook/ 

    - name: Run notebook
      run: |
        jupyter nbconvert --to notebook --execute notebook/iadt_fase01_final.ipynb --output executed_notebook.ipynb
